name: Deploy to EC2

on:
  push:
    branches:
      - main   # 👈 Change if you want another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meta_manager:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/meta_manager:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/meta_manager:latest
            docker stop my-flask-app || true
            docker rm my-flask-app || true
            docker run -d -p 4000:4000 --name my-flask-app ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
